"""Build the console's graph-explorer bundle from a graphify graph.json (build plane).

graph.json is the MCP runtime's format: networkx node_link_data with every
extraction attribute, 12–80 MB for mid-size repos — far too heavy for a
browser tab and lacking positions. This script writes, next to it:

  viz.json       compact, columnar, GZIP-COMPRESSED (published to S3 with
                 Content-Encoding: gzip so fetch() decodes transparently):
                 dictionaries (types/kinds/relations/files/repos), per-node
                 columns (id/label/community/type/kind/file/loc/degree/x/y),
                 integer-indexed edges, community summaries + inter-community
                 edge weights, hyperedges. ~30x smaller than graph.json.
  viz-meta.json  a ~1 KB header (stats, layout kind, bundle sizes, build id),
                 inlined by the platform API so the console can show a
                 summary before downloading the bundle.

Layout is precomputed here (python-igraph, no LLM) as a TWO-LEVEL layout:
Fruchterman-Reingold on the community meta-graph (weighted by cross-community
edge counts) places each community; a local FR lays out each community's
members inside a disc whose radius grows with sqrt(size); a grid-hashed
relaxation pushes overlapping discs apart. Communities are therefore visually
distinct clusters, and a community's aggregate-view position IS the centroid
of its members, so drilling down zooms into the same place. Cost is driven by
the COMMUNITY count, not the node count (exact meta FR and the disc relaxation
are quadratic in it): 1.5k communities ≈ 3 s, 4k ≈ 15 s, 16k ≈ 4 min on this
path — so above MAX_FR_COMMUNITIES the meta layout switches to DrL and above
MAX_LAYOUT_COMMUNITIES x/y are skipped (the console lays out client-side).
Coordinates are normalized to [-1000, 1000].

Best-effort by contract: the buildspec runs this with `|| echo` — a viz
failure must never fail a graph build. Community ids are unstable across
rebuilds (Leiden is non-deterministic), so nothing here is keyed on them
beyond this one bundle.

Usage: python make_viz.py --graph <graph.json> --out-dir <dir> [--repo-id ID]
       [--labels <.graphify_labels.json>] [--max-nodes N]
"""

from __future__ import annotations

import argparse
import collections
import gzip
import json
import math
import random
import re
import sys
import time
from pathlib import Path

import igraph as ig

# python-igraph draws its layout randomness from Python's `random`: seed it so
# the same graph always gets the same picture (the hub is regenerated by every
# build of every repo and must not reshuffle each time).
random.seed(0)

EXTENT = 1000.0
MAX_LABEL = 200
# Above this, skip x/y entirely (the browser lays out or shows aggregate only)
# — the local-FR pass is linear but a 500k-node graph is not a browser target.
DEFAULT_MAX_LAYOUT_NODES = 300_000
# Community-count guards (the quantity that actually drives layout cost).
MAX_FR_COMMUNITIES = 4_000        # exact meta FR above this → DrL (11 s @16k vs 83 s)
MAX_LAYOUT_COMMUNITIES = 12_000   # above this skip x/y entirely; the browser lays out
# Labels come from untrusted repos/docs (and the hub bundle mixes tenants):
# strip C0/C1 controls plus zero-width and bidi-override code points, which
# spoof what the canvas shows. The console re-sanitizes as defense in depth.
_CTRL = re.compile(
    "[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f"  # C0/C1 controls
    "\u200b-\u200f\u2028\u2029\u202a-\u202e\u2066-\u2069\ufeff]"  # zero-width, bidi, BOM
)


def clean(s, limit: int = MAX_LABEL) -> str:
    s = _CTRL.sub("", str(s if s is not None else ""))
    return s if len(s) <= limit else s[: limit - 1] + "…"


def dictify(values):
    """Values -> (table, index list). Empty/None map to ""."""
    table: dict[str, int] = {}
    out = []
    for v in values:
        v = clean(v, 512) if v is not None else ""
        i = table.get(v)
        if i is None:
            i = table[v] = len(table)
        out.append(i)
    return list(table), out


def normalize(coords, extent: float):
    xs = [c[0] for c in coords]
    ys = [c[1] for c in coords]
    cx = (max(xs) + min(xs)) / 2
    cy = (max(ys) + min(ys)) / 2
    span = max(max(xs) - min(xs), max(ys) - min(ys)) or 1.0
    k = 2 * extent / span
    return [((x - cx) * k, (y - cy) * k) for x, y in coords]


def relax_discs(centers, radii, rounds: int | None = None):
    """Push overlapping discs apart. Grid-hashed on a cell sized by the TYPICAL
    disc (90th-percentile radius) so thousands of communities stay cheap. Discs
    wider than a cell would slip through the grid, so the LARGEST few (an
    absolute cap — a percentile would be ~10% of n and make this quadratic)
    are checked against everything; the rounds budget shrinks with n. Residual
    overlap on a giant disc is a cosmetic miss on a read-side nicety."""
    n = len(centers)
    if n < 2:
        return centers
    if rounds is None:
        rounds = min(60, max(8, 400_000 // n))
    p90 = sorted(radii)[min(n - 1, int(n * 0.9))]
    cell = max(p90 * 2, 1.0)
    by_radius = sorted(range(n), key=lambda i: -radii[i])
    big = [i for i in by_radius[:64] if radii[i] > cell / 2]
    big_set = set(big)
    small = [i for i in range(n) if i not in big_set]
    pts = [list(c) for c in centers]

    def push_apart(i, j) -> bool:
        dx = pts[j][0] - pts[i][0]
        dy = pts[j][1] - pts[i][1]
        d = math.hypot(dx, dy)
        need = radii[i] + radii[j]
        if d >= need:
            return False
        if d < 1e-6:
            dx, dy, d = 1.0, 0.0, 1.0
        push = (need - d) / 2 + 0.5
        ux, uy = dx / d, dy / d
        pts[i][0] -= ux * push
        pts[i][1] -= uy * push
        pts[j][0] += ux * push
        pts[j][1] += uy * push
        return True

    for _ in range(rounds):
        grid: dict[tuple[int, int], list[int]] = collections.defaultdict(list)
        for i in small:
            grid[(int(pts[i][0] // cell), int(pts[i][1] // cell))].append(i)
        moved = False
        for (gx, gy), members in list(grid.items()):
            cand = []
            for dx in (-1, 0, 1):
                for dy in (-1, 0, 1):
                    cand.extend(grid.get((gx + dx, gy + dy), ()))
            for i in members:
                for j in cand:
                    if j > i and push_apart(i, j):
                        moved = True
        for i in big:
            for j in range(n):
                if j != i and (j not in big_set or j > i) and push_apart(i, j):
                    moved = True
        if not moved:
            break
    return [(p[0], p[1]) for p in pts]


def two_level_layout(g: ig.Graph, cid_of: list[int]):
    """Community meta-graph FR -> per-community local FR inside sqrt-sized discs."""
    comms: dict[int, list[int]] = collections.defaultdict(list)
    for v, c in enumerate(cid_of):
        comms[c].append(v)
    cids = sorted(comms)
    cidx = {c: i for i, c in enumerate(cids)}
    weights: collections.Counter = collections.Counter()
    for e in g.es:
        a, b = cid_of[e.source], cid_of[e.target]
        if a != b:
            weights[(min(a, b), max(a, b))] += 1
    meta = ig.Graph(n=len(cids), edges=[(cidx[a], cidx[b]) for (a, b) in weights], directed=False)
    sizes = [len(comms[c]) for c in cids]
    radii = [13.0 * math.sqrt(s) + 7.0 for s in sizes]
    if len(cids) == 1:
        centers = [(0.0, 0.0)]
    else:
        # grid="nogrid" is load-bearing: igraph's default grid="auto" switches
        # to the grid approximation at >=1000 vertices, and on these graphs
        # that collapses everything into a central blob with a sparse halo
        # (measured: 4% canvas occupancy). Exact FR on the meta-graph is cheap
        # (hub: 1.5k communities); 200 iterations measured as good as 700.
        if meta.ecount():
            meta.es["weight"] = [weights[k] for k in weights]
            if len(cids) <= MAX_FR_COMMUNITIES:
                ml = meta.layout_fruchterman_reingold(weights="weight", niter=200, grid="nogrid")
            else:
                # Exact FR is quadratic in the community count; DrL keeps the
                # meta-graph readable at 10x lower cost for very fragmented graphs.
                ml = meta.layout_drl(weights="weight")
        else:
            ml = meta.layout_circle()
        # PRISM-style pre-scale: size the meta layout so discs fill ~45% of the
        # bounding area BEFORE overlap removal, so the relaxation only has to
        # nudge (60 rounds, sub-second) instead of inventing all the space.
        area = sum(math.pi * r * r for r in radii)
        half = max(math.sqrt(area / 0.45) / 2, max(radii) * 2)
        centers = relax_discs(normalize([(p[0], p[1]) for p in ml], half), radii)
    pos: list[tuple[float, float] | None] = [None] * g.vcount()
    for c, members in comms.items():
        cx, cy = centers[cidx[c]]
        r = radii[cidx[c]] * 0.85
        if len(members) == 1:
            pos[members[0]] = (cx, cy)
            continue
        if len(members) <= 3:
            for k, v in enumerate(members):
                ang = 2 * math.pi * k / len(members)
                pos[v] = (cx + r * 0.5 * math.cos(ang), cy + r * 0.5 * math.sin(ang))
            continue
        sub = g.induced_subgraph(members)
        # Exact FR is O(n²)/iteration: fine for real communities (p90 ≈ 45
        # members) but a cluster-only failure can leave one community holding
        # the whole graph — the grid approximation is acceptable INSIDE a disc.
        ll = sub.layout_fruchterman_reingold(niter=300 if len(members) <= 3000 else 150,
                                             grid="nogrid" if len(members) <= 3000 else "grid")
        loc = normalize([(p[0], p[1]) for p in ll], r)
        for k, v in enumerate(members):
            pos[v] = (cx + loc[k][0], cy + loc[k][1])
    return normalize(pos, EXTENT)  # type: ignore[arg-type]


def derive_community_meta(nodes, members, deg, type_idx, files):
    """Dominant directory / document + hub nodes, for auto-labelling communities
    whose only name is the generic 'Community N' (no LLM labelling ran)."""
    dirs: collections.Counter = collections.Counter()
    for i in members:
        sf = files[i] or ""
        if not sf:
            continue
        parts = sf.split("/")
        # Root-level files count toward the repo root (""), not their own name.
        key = "/".join(parts[:-1][:2]) if len(parts) > 1 else ""
        dirs[key] += 1
    top_dir, top_n = dirs.most_common(1)[0] if dirs else ("", 0)
    hubs = sorted(members, key=lambda i: (-deg[i], i))[:3]
    dom_type = collections.Counter(type_idx[i] for i in members).most_common(1)[0][0]
    return top_dir, round(top_n / max(len(members), 1), 2), hubs, dom_type


_PAGE_LOC = re.compile(r"^p\.(\d+)")
# Any heading level: convert_docs now nests page markers under section
# headings ("##### <stem> — p.N"); older sidecars used "##".
_PAGE_HEADING = re.compile(r"^#{2,6} .* — p\.(\d+)\s*$")
_LINE_LOC = re.compile(r"^L\d+")
_LABEL_MIN_CHARS = 3


def _doc_index(src_dir: Path, rel: str, cache: dict) -> tuple[dict[int, int], list[str]]:
    """(page -> line) map and lower-cased lines of one source file, cached per file."""
    if rel not in cache:
        pages: dict[int, int] = {}
        lowered: list[str] = []
        try:
            for i, line in enumerate((src_dir / rel).read_text(encoding="utf-8", errors="replace").splitlines(), 1):
                pm = _PAGE_HEADING.match(line)
                if pm:
                    pages.setdefault(int(pm.group(1)), i)
                lowered.append(line.lower())
        except OSError:
            pass
        cache[rel] = (pages, lowered)
    return cache[rel]


def resolve_doc_locs(nodes: list[dict], src_dir: Path) -> tuple[int, int]:
    """Give document-derived nodes a line the console's source viewer can open on.

    Code nodes carry "L<line>" from the AST. Document nodes do not: the quick
    scan gives headings a line, but LLM extraction cites pages ("p.3",
    "p.21-24", "p.3, p.5") for PDF/Office sidecars (convert_docs.py writes one
    "## <stem> — p.N" heading per page) and leaves concept/entity nodes with a
    file and no location at all. Two resolutions, in order:
      1. page citation  -> the page heading's line, stored as "L<line> (p.N)"
      2. no usable line -> the first line mentioning the node's label
                           (case-insensitive), stored as "L<line> (~)"
    The console parses the leading L<line>; the suffix stays visible. Only the
    bundle changes — graph.json on disk is untouched. Returns (pages, labels)."""
    cache: dict = {}
    pages_hit = labels_hit = 0
    for n in nodes:
        rel = n.get("source_file")
        if not isinstance(rel, str) or not rel:
            continue
        loc = str(n.get("source_location") or "")
        if _LINE_LOC.match(loc):
            continue
        pm = _PAGE_LOC.match(loc)
        if pm:
            pages, _ = _doc_index(src_dir, rel, cache)
            line_no = pages.get(int(pm.group(1)))
            if line_no:
                n["source_location"] = f"L{line_no} ({loc})"
                pages_hit += 1
                continue
        label = str(n.get("label") or "").strip().lower()
        # LLM labels often carry a qualifier the text does not: "ISO 27014
        # (정보보호 거버넌스 국제표준)" → retry with the part before "(".
        needles = [label] + ([label.split("(", 1)[0].strip()] if "(" in label else [])
        needles = [x for x in needles if len(x) >= _LABEL_MIN_CHARS]
        if not needles:
            continue
        _, lowered = _doc_index(src_dir, rel, cache)
        for needle in needles:
            line_no = next((i for i, line in enumerate(lowered, 1) if needle in line), 0)
            if line_no:
                n["source_location"] = f"L{line_no} (~)"
                labels_hit += 1
                break
    return pages_hit, labels_hit


def build(graph_path: Path, labels_path: Path | None, repo_id: str, max_layout_nodes: int, src_dir: Path | None = None) -> tuple[dict, dict]:
    t0 = time.time()
    data = json.loads(graph_path.read_text(encoding="utf-8"))
    nodes = [n for n in (data.get("nodes") or []) if isinstance(n, dict) and isinstance(n.get("id"), str)]
    links = [l for l in (data.get("links") or data.get("edges") or []) if isinstance(l, dict)]
    if src_dir is not None:
        pages_hit, labels_hit = resolve_doc_locs(nodes, src_dir)
        if pages_hit or labels_hit:
            print(f"[make_viz] document locations resolved: {pages_hit} page citations, {labels_hit} label matches", file=sys.stderr)
    labels: dict[int, str] = {}
    if labels_path and labels_path.exists():
        try:
            raw = json.loads(labels_path.read_text(encoding="utf-8"))
            if isinstance(raw, dict) and isinstance(raw.get("labels"), dict):
                raw = raw["labels"]
            for k, v in (raw.items() if isinstance(raw, dict) else []):
                if isinstance(v, dict):
                    v = v.get("label") or v.get("name") or v.get("title") or ""
                try:
                    if isinstance(v, str) and v.strip():
                        labels[int(k)] = clean(v)
                except (TypeError, ValueError):
                    continue
        except Exception as exc:  # labels are optional polish
            print(f"[make_viz] labels unreadable ({exc}); using graph.json community_name", file=sys.stderr)

    idx = {n["id"]: i for i, n in enumerate(nodes)}
    edges: list[tuple[int, int]] = []
    kept_links = []
    for l in links:
        src, tgt = l.get("source"), l.get("target")
        if not isinstance(src, str) or not isinstance(tgt, str):
            continue
        s, t = idx.get(src), idx.get(tgt)
        if s is None or t is None:
            continue
        edges.append((s, t))
        kept_links.append(l)
    g = ig.Graph(n=len(nodes), edges=edges, directed=False)
    simple = g.copy()
    simple.simplify()
    deg = simple.degree()

    cid_of = []
    for n in nodes:
        c = n.get("community")
        try:
            cid_of.append(int(c) if c is not None else -1)
        except (TypeError, ValueError):
            cid_of.append(-1)

    layout_kind = None
    xs = ys = None
    n_comms = len(set(cid_of))
    if len(nodes) and len(nodes) <= max_layout_nodes and n_comms <= MAX_LAYOUT_COMMUNITIES:
        t = time.time()
        pos = two_level_layout(simple, cid_of)
        xs = [round(p[0], 1) for p in pos]
        ys = [round(p[1], 1) for p in pos]
        layout_kind = "two-level-fr"
        print(f"[make_viz] layout {layout_kind}: {len(nodes)} nodes in {time.time() - t:.1f}s")
    else:
        print(f"[make_viz] layout skipped ({len(nodes)} nodes / {n_comms} communities exceed the caps)")

    types, t_idx = dictify([n.get("file_type") for n in nodes])
    kinds, k_idx = dictify([n.get("node_kind") for n in nodes])
    file_list, f_idx = dictify([n.get("source_file") for n in nodes])
    rels, r_idx = dictify([l.get("relation") for l in kept_links])
    has_repo = any("repo" in n for n in nodes)
    repos, rp_idx = dictify([n.get("repo") for n in nodes]) if has_repo else ([], None)
    files_of_node = [clean(n.get("source_file") or "", 512) for n in nodes]

    comm_members: dict[int, list[int]] = collections.defaultdict(list)
    for i, c in enumerate(cid_of):
        comm_members[c].append(i)
    communities = []
    for c in sorted(comm_members, key=lambda c: (-len(comm_members[c]), c)):
        m = comm_members[c]
        name = labels.get(c) or clean(nodes[m[0]].get("community_name") or "")
        auto = not name or bool(re.fullmatch(r"Community \d+", name))
        if auto:
            # Merged hub nodes carry their PRE-merge "Community N"; use this
            # graph's own id so labels never collide across repos.
            name = f"Community {c}"
        top_dir, share, hubs, dom_type = derive_community_meta(nodes, m, deg, t_idx, files_of_node)
        entry = {
            "id": c, "label": name or f"Community {c}", "auto": auto, "size": len(m),
            "dir": clean(top_dir, 160), "dir_share": share, "hubs": hubs, "type": dom_type,
        }
        if xs is not None:
            entry["x"] = round(sum(xs[i] for i in m) / len(m), 1)
            entry["y"] = round(sum(ys[i] for i in m) / len(m), 1)
        communities.append(entry)
    cw: collections.Counter = collections.Counter()
    for (a, b) in edges:
        ca, cb = cid_of[a], cid_of[b]
        if ca != cb:
            cw[(min(ca, cb), max(ca, cb))] += 1
    cedges = [[a, b, n] for (a, b), n in sorted(cw.items(), key=lambda kv: -kv[1])]

    hyperedges = []
    for h in data.get("hyperedges") or []:
        if not isinstance(h, dict):
            continue
        members = [idx[x] for x in (h.get("nodes") or []) if isinstance(x, str) and x in idx]
        if len(members) >= 2:
            hyperedges.append({"label": clean(h.get("label") or h.get("relation") or ""), "nodes": members})

    header = {
        "v": 1,
        "repo_id": repo_id,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "built_at_commit": data.get("built_at_commit") or "",
        "layout": layout_kind,
        "stats": {
            "nodes": len(nodes), "edges": len(kept_links), "communities": len(communities),
            "isolated": sum(1 for d in deg if d == 0), "files": len(file_list),
            "types": dict(collections.Counter(types[i] for i in t_idx)),
            "relations": dict(collections.Counter(rels[i] for i in r_idx)),
            "inferred_edges": sum(1 for l in kept_links if l.get("confidence") == "INFERRED"),
            "repos": len(repos),
        },
    }
    bundle = dict(header)
    bundle.update({
        "types": types, "kinds": kinds, "relations": rels, "repos": repos, "files": file_list,
        "communities": communities, "cedges": cedges,
    })
    bundle["nodes"] = {
        "id": [clean(n["id"], 512) for n in nodes],
        "label": [clean(n.get("label") or n["id"]) for n in nodes],
        "c": cid_of, "t": t_idx, "k": k_idx, "f": f_idx,
        "loc": [clean(n.get("source_location") or "", 40) for n in nodes],
        "deg": deg,
    }
    if xs is not None:
        bundle["nodes"]["x"] = xs
        bundle["nodes"]["y"] = ys
    if rp_idx is not None:
        bundle["nodes"]["r"] = rp_idx
    bundle["edges"] = {
        "s": [e[0] for e in edges], "t": [e[1] for e in edges], "r": r_idx,
        "inf": [1 if l.get("confidence") == "INFERRED" else 0 for l in kept_links],
    }
    bundle["hyperedges"] = hyperedges
    print(f"[make_viz] {len(nodes)} nodes / {len(kept_links)} edges / {len(communities)} communities in {time.time() - t0:.1f}s")
    return header, bundle


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--graph", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--repo-id", default="")
    ap.add_argument("--labels", default="")
    ap.add_argument("--max-nodes", type=int, default=DEFAULT_MAX_LAYOUT_NODES)
    ap.add_argument("--src-dir", default="", help="source checkout; resolves page citations (p.N) to sidecar lines")
    args = ap.parse_args()
    graph_path = Path(args.graph)
    labels_path = Path(args.labels) if args.labels else graph_path.with_name(".graphify_labels.json")
    header, bundle = build(graph_path, labels_path, args.repo_id, args.max_nodes, Path(args.src_dir) if args.src_dir else None)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    raw = json.dumps(bundle, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    gz = gzip.compress(raw, 9)
    (out / "viz.json.gz").write_bytes(gz)
    header["bundle_bytes"] = len(gz)
    header["bundle_raw_bytes"] = len(raw)
    (out / "viz-meta.json").write_text(json.dumps(header, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print(f"[make_viz] viz.json.gz {len(gz)} bytes (raw {len(raw)}), viz-meta.json {len(json.dumps(header))} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
